// TODO : convert to real data
export const wardensData = [
  // Mock Data - Replace this with actual data
  {
    key: "1",
    wardenId: "EFH238",
    wardenName: "Naomi Doe",
    hostelName: "Downing Hostel",
    address: "123, downing street",
    createdAt: "12-Mar-2024",
    email: "naomi@gmail.com",
    phoneNumber: "+92 123-4567890",
    type: "Student Accommodation",
    totalRooms: "05",
    status: "new",
  },
  {
    key: "2",
    wardenId: "EFH239",
    wardenName: "Naomi Doe",
    hostelName: "My Hostel",
    address: "123, downing street",
    email: "naomi@gmail.com",
    phoneNumber: "+92 123-4567890",
    createdAt: "12-Mar-2024",
    type: "Student Accommodation",
    totalRooms: "05",
    status: "new",
  },
  {
    key: "3",
    wardenId: "EFH240",
    wardenName: "Naomi Doe",
    hostelName: "Your Hostel",
    address: "123, downing street",
    email: "naomi@gmail.com",
    phoneNumber: "+92 123-4567890",
    createdAt: "12-Mar-2024",
    type: "Student Accommodation",
    totalRooms: "05",
    status: "active",
  },
  {
    key: "4",
    wardenId: "EFH241",
    wardenName: "Naomi Doe",
    hostelName: "His Hostel",
    address: "123, downing street",
    email: "naomi@gmail.com",
    phoneNumber: "+92 123-4567890",
    createdAt: "12-Mar-2024",
    type: "Student Accommodation",
    totalRooms: "05",
    status: "banned",
  },
  {
    key: "5",
    wardenId: "EFH242",
    wardenName: "Naomi Doe",
    hostelName: "His Hostel",
    address: "123, downing street",
    email: "naomi@gmail.com",
    phoneNumber: "+92 123-4567890",
    createdAt: "12-Mar-2024",
    type: "Student Accommodation",
    totalRooms: "05",
    status: "rejected",
  },
];

// TODO : convert to real data
export const adminDetails = {
  fullName: "Naomi Doe",
  profilePicture: "",
  dateOfBirth: "14-11-2000",
  email: "naomi@gmail.com",
  phoneNumber: "+92 123-4567890",
  currentAddress: "123, Downing street, China town.",
  currentState: "Punjab",
  currentPassword: "12345678",
  newPassword: "",
  confirmPassword: "",
};

export const dashBoardData = {
  totalHostels: "10",
  totalResidents: "150k",
  chartData: {
    labels: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    datasets: [
      {
        label: "Total Hostels Created",
        data: [10, 30, 50, 150, 140, 120, 110, 90, 80, 60, 30, 10],
        fill: false,
        borderColor: "#007bff",
        tension: 0.1,
        pointBackgroundColor: "#fff",
        pointBorderColor: "#007bff",
        pointHoverBackgroundColor: "#007bff",
        pointHoverBorderColor: "#fff",
        pointRadius: 5,
        pointHoverRadius: 8,
      },
    ],
  },
};

// TODO : convert to real data
export const hostelDetailsTableData = [
  {
    key: 1,
    roomNumber: "DH-01",
    roomType: "Bunker Room",
    numberOfBeds: "04",
    washroom: "01",
    seatsAvailable: "02",
    roomPricePerSeat: "Rs. 14,000",
  },
  {
    key: 2,
    roomNumber: "DH-01",
    roomType: "Bunker Room",
    numberOfBeds: "04",
    washroom: "01",
    seatsAvailable: "02",
    roomPricePerSeat: "Rs. 14,000",
  },
  {
    key: 3,
    roomNumber: "DH-01",
    roomType: "Bunker Room",
    numberOfBeds: "04",
    washroom: "01",
    seatsAvailable: "02",
    roomPricePerSeat: "Rs. 14,000",
  },
  {
    key: 4,
    roomNumber: "DH-01",
    roomType: "Bunker Room",
    numberOfBeds: "04",
    washroom: "01",
    seatsAvailable: "02",
    roomPricePerSeat: "Rs. 14,000",
  },
  {
    key: 5,
    roomNumber: "DH-01",
    roomType: "Bunker Room",
    numberOfBeds: "04",
    washroom: "01",
    seatsAvailable: "02",
    roomPricePerSeat: "Rs. 14,000",
  },
  {
    key: 6,
    roomNumber: "DH-01",
    roomType: "Bunker Room",
    numberOfBeds: "04",
    washroom: "01",
    seatsAvailable: "02",
    roomPricePerSeat: "Rs. 14,000",
  },
];

// TODO : convert to real data
export const hostelDetailsDescriptionData = {
  title: "Description",
  description: [
    "Lorem ipsum dolor sit amet consectetur. Lobortis quis ornare est velit cursus quam gravida tellus lobortis. Eget ut adipiscing convallis fames pretium sed pellentesque sit eget. Tristique dignissim vel tortor adipiscing quis ultricies. Massa odio duis risus orci maecenas in massa eget eget.",
    "Lorem ipsum dolor sit amet consectetur. Vitae sagittis eget diam lacus. Sapien cras mauris sollicitudin dolor nec enim imperdiet.",
    "Lorem ipsum dolor sit amet consectetur. At nibh pretium turpis tellus. Sit gravida non praesent nunc. Congue aliquam convallis malesuada amet diam orci vitae at vel. Maecenas sapien vestibulum morbi placerat id. Posuere venenatis mauris quam nisl aenean sed nulla vel. Tellus aliquet curabitur risus quis molestie iaculis pretium viverra vulputate. Libero porttitor quam vestibulum congue luctus amet. Et eget pharetra quis ac adipiscing eros sagittis justo lacus. Nibh cras tempus aenean mauris gravida lectus. Volutpat tincidunt enim arcu turpis est varius condimentum ut. Duis congue nunc faucibus turpis porttitor.",
    "Lorem ipsum dolor sit amet consectetur. In dictum ipsum quis ullamcorper elit malesuada eget augue. Vel sed neque vulputate lectus urna faucibus ac pellentesque.",
  ],
};
